# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ADD_YOUR_APP_NAME"
client_id = "ADD_YOUR_CLIENT_ID"
application_url = "https://crew-la-jokes-genius.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://crew-la-jokes-genius.trycloudflare.com/auth/callback",
  "https://crew-la-jokes-genius.trycloudflare.com/auth/shopify/callback",
  "https://crew-la-jokes-genius.trycloudflare.com/api/auth/callback",
  "https://crew-la-jokes-genius.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "DEV_STORE.myshopify.com"
